image: maven:3.6.3-jdk-8

stages:
  - build

build:
  stage: build
  script:
    - mvn verify --batch-mode --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn